### ISSUE TITLE
[Bug]: storeExplosions can make the game lag badly

### ISSUE THREAD

**Issue by Dr-WeiAL** [Mrbysco/BlockHistory#3]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.11

### Minecraft version

1.19.2

### Mod version

1.2.1

### Java version

JDK 17

### Issue Description

Any explosion will cause the game to lag for a few seconds
It seems to be a sql problem?
![image](https://github.com/Mrbysco/BlockHistory/assets/47446553/ab8a3b60-fd6b-4903-815d-c7239d255183)

https://spark.lucko.me/optBrNdhqw

**Comment by Mrbysco** [comment]
I'll see about adding a bulk add method that adds them all in 1 transaction. I already got a test build but Github doesn't allow me to embed it in here

**Comment by Dr-WeiAL** [comment]
I joined your Discord, maybe you can send files there?
I sent you a private message
