### ISSUE TITLE
[Bug]: Event implementations require player to be non null

### ISSUE THREAD

**Issue by Thodor12** [Mrbysco/BlockHistory#9]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

47.3.0

### Minecraft version

1.20.1

### Mod version

1.3.0

### Java version

17

### Issue Description

All events require the player to be loaded (I.e. [here](https://github.com/Mrbysco/BlockHistory/blob/1.20/src/main/java/com/mrbysco/blockhistory/handler/ModifyHandler.java#L35)).

An end user using our mod Minecolonies reported your mod crashing because some of our citizen entities (in this case the farmer) modify blocks which cause a hit in your event handler.
However there's no player here, which is allowed because in all events the player is nullable.

Your event handlers should ensure the player may be null and not run if no player is supplied, or find some kind of workaround where you don't know the player.
Level for example can be obtained through the use context and the name could default to not using the player name if none is found.

### Additional Information

https://gist.github.com/Patrumn/0018fbd88d9f54d5a25dcd4012e919ba

**Comment by Mrbysco** [comment]
A new version is being uploaded fixing this problem
